# Generated by Django 5.0.6 on 2024-06-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeneratedPasswordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cathegory', models.CharField(choices=[('Sport', 'Sport'), ('Social media', 'Social media'), ('Programming and IT', 'Programming and IT'), ('Coocking', 'Coocking'), ('Art / Drawing', 'Art / Drawing'), ('Math', 'Math'), ('Language', 'Language'), ('Science', 'Science'), ('Robotics', 'Robotics'), ('Dancing', 'Dancing'), ('Dancing', 'Dancing'), ('Music / Singing', 'Music / Singing'), ('Video games', 'Video games'), ('Yoga / Mediatation', 'Yoga / Mediatation'), ('Martial arts', 'Martial arts'), ('Design', 'Design'), ('School / University', 'School / University')], max_length=30)),
                ('password', models.CharField(max_length=45)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_authentication.userprofilemodel')),
            ],
        ),
    ]
