# Generated by Django 5.0.6 on 2024-06-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_dashboard', '0001_initial'),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGeneratedPasswordsModel',
            new_name='UserGeneratedPasswordModel',
        ),
    ]
