# Generated by Django 5.0.6 on 2024-06-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_dashboard', '0002_rename_usergeneratedpasswordsmodel_usergeneratedpasswordmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergeneratedpasswordmodel',
            old_name='cathegory',
            new_name='category',
        ),
    ]
